relativeURLs = true
title = "Jitendra Aswani"
theme = "academimal1"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Post-Doctoral Researcher, Harvard University; Ph.D. (Finance), Fordham University"
    logo = "jeetprofilepic2.jpg" 
    
